### ISSUE TITLE
boilerplate starter template?

### ISSUE THREAD

**Issue by kristianmandrup** [eploko/pegjs-loader#11]
Would love if there was a generator or quick start boilerplate project using this for getting started with PEG.js

**Comment by eploko** [comment]
@kristianmandrup thanks for the idea, but I doubt it's a high priority. This is a webpack loader after all and its usage is similar to tons of other loaders. The options available are outlined in the README and this is so far the greatest struggle to anyone choosing to use a new loader, IMHO.

Anyway, if you come up with a PR for this, I'd be more than happy to merge it in. Or we can just add a link to README if such a boilerplate exists.

Please feel free to re-open this issue as needed.
