### ISSUE TITLE
Webpack peer dependency: remove?

### ISSUE THREAD

**Issue by james-criscuolo** [eploko/pegjs-loader#12]
I implemented this project in my webpack config with the latest webpack (3.1.0) only to find the peer dependency warning crop up. This normally wouldn't be an issue, but I do run my project through Travis, where it seems like these issues can't be ignored.

Webpack@3 is fairly new, but there was a previous PR to get webpack@2 included in the peer dependencies, and if I open one for 3, there's nothing stopping 4 from not working in the future.

Is it a justifiable solution to just remove the peer dependency, or make it more future-proof at least? Just make it like `> 1` or something like that.

**Comment by Izhaki** [comment]
Same here. Works with webpack 3.1.0.
