### ISSUE TITLE
SQLite grammar not parsing

### ISSUE THREAD

**Issue by krzysztofpniak** [eploko/pegjs-loader#13]
https://github.com/codeschool/sqlite-parser/blob/master/src/grammar.pegjs

I cant' figure out why this file raises the error.

**Comment by eploko** [comment]
Hey @krzysztofpniak, unfortunatelly I can't provide any advice on that. Please let me know if there's anything in the loader that needs to be fixed to parse the grammar if you still need that. Meanwhile, I'm closing this issue.
