### ISSUE TITLE
pegjs 0.10.0 breaks pegjs-loader

### ISSUE THREAD

**Issue by tomxtobin** [eploko/pegjs-loader#5]
[The API changed][api-changed]:

> The `peg.buildParser` function was renamed to `peg.generate`.

[api-changed]: https://github.com/pegjs/pegjs/blob/master/CHANGELOG.md#0100

**Comment by VladimirTechMan** [comment]
@tomxtobin I have previously sent my pull request to @eploko on that. See details at https://github.com/eploko/pegjs-loader/pull/4. Hopefully, he is still around and will take care of it.

In the meantime, if you are okay to manually merge that change (it's a simple small diff), you can DIY.

**Comment by tomxtobin** [comment]
@VladimirTechMan Thanks for pointing that out! There's nothing urgent I need (yet) from 0.10, but if that changes I'll probably go ahead and apply your patch. (But hopefully it gets applied before then.) ;-)

**Comment by tomxtobin** [comment]
@eploko Are you still maintaining this project? It's been a month since PegJS updated, and this issue is a blocker for anyone wanting to use pegjs-loader against the current version of PegJS.

**Comment by eploko** [comment]
I'm sorry for the hiccup and the delay. Merged. Thanks a ton for nudging me :)

**Comment by eploko** [comment]
The updated version is now on npm as 0.5.0.

**Comment by VladimirTechMan** [comment]
Fantastic! Thanks, @eploko. I am glad to know that you can still take care of this repository and the npm package.
